### ISSUE TITLE
Tradução pra ENG

### ISSUE THREAD

**Issue by CarlosJunioor** [calixtocarolina/Pensamento-Computacional#1]
Me proponho a traduzir o repo para inglês com o intuito de aumentar o alcance do público que pode acessar a este repo, e adicionar imagens relativas ao tema.

**Comment by calixtocarolina** [comment]
Oi Carlos, muito obrigada por sua contribuição. Você recomenda eu adicionar um update no próprio repositório ou criar outro com o mesmo conteúdo, traduzido pro inglês? 
Em relação às imagens, estou pesquisando uma forma de fazer a documentação ficar mais interativa com o uso de imagens, se você tiver sugestões, ficaria feliz em recebê-las!

**Comment by CarlosJunioor** [comment]
Seria legal possuir 2 README files, e o principal com um botão no inicio do readme para ele redirecionar para a página o README em eng.

Em relação as imagens, irei mandar algumas.

**Comment by calixtocarolina** [comment]
Ok, obrigada! Para me enviar as imagens, caso queira, pode adicionar pela issue via link ou me enviar em alguma rede social (está no meu readme).
